spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/english    # schema englishcard
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true
upload:
  path: C:\\Users\\User\\new